FROM golang:1.14.3-alpine as builder

WORKDIR /go/src/go-grpc

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/server ./cmd/server
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server ./cmd/server

######## Start a new stage from scratch #######
FROM alpine:3.11.6  

WORKDIR /root/

COPY --from=builder /go/src/go-grpc/server .
COPY ./ssl ./ssl

EXPOSE 4000

# Command to run the executable
CMD ["./server"] 