// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreServiceClient interface {
	Order(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

var storeServiceOrderStreamDesc = &grpc.StreamDesc{
	StreamName: "Order",
}

func (c *storeServiceClient) Order(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/Order", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceService is the service API for StoreService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterStoreServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type StoreServiceService struct {
	Order func(context.Context, *OrderRequest) (*OrderResponse, error)
}

func (s *StoreServiceService) order(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/store.StoreService/Order",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Order(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterStoreServiceService registers a service implementation with a gRPC server.
func RegisterStoreServiceService(s grpc.ServiceRegistrar, srv *StoreServiceService) {
	srvCopy := *srv
	if srvCopy.Order == nil {
		srvCopy.Order = func(context.Context, *OrderRequest) (*OrderResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Order not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "store.StoreService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Order",
				Handler:    srvCopy.order,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "store.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewStoreServiceService creates a new StoreServiceService containing the
// implemented methods of the StoreService service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewStoreServiceService(s interface{}) *StoreServiceService {
	ns := &StoreServiceService{}
	if h, ok := s.(interface {
		Order(context.Context, *OrderRequest) (*OrderResponse, error)
	}); ok {
		ns.Order = h.Order
	}
	return ns
}

// UnstableStoreServiceService is the service API for StoreService service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableStoreServiceService interface {
	Order(context.Context, *OrderRequest) (*OrderResponse, error)
}
